# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# ============================================================
# Head joints
# ============================================================

# Head rotate (z)
head_r_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: head_r_joint
  pid: {p: 1000.0, i: 0.01, d: 10}

# Head side turn (y)
head_s_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: head_s_joint
  pid: {p: 1000.0, i: 0.01, d: 10}

# head forward/backward turn (x)
head_f_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: head_f_joint
  pid: {p: 1000.0, i: 0.01, d: 10}

# Neck forward/backward turn (x)
neck_f_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: neck_f_joint
  pid: {p: 1000.0, i: 0.01, d: 10}

# ============================================================
# Left arm joints
# ============================================================

# Shoulder forward/backward turn (x)
shoulder_f_joint_left_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_f_joint_left
  pid: {p: 1000.0, i: 0.01, d: 10}

# Shoulder side turn (y)
shoulder_s_joint_left_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_s_joint_left
  pid: {p: 1000.0, i: 0.01, d: 10}

# ============================================================
# Right arm joints
# ============================================================

# Shoulder forward/backward turn (x)
shoulder_f_joint_right_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_f_joint_right
  pid: {p: 1000.0, i: 0.01, d: 10}

# Shoulder side turn (y)
shoulder_s_joint_right_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_s_joint_right
  pid: {p: 1000.0, i: 0.01, d: 10}

# ============================================================
# Body joints
# ============================================================

# Torso rotate (z)
torso_r_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: torso_r_joint
  pid: {p: 1000.0, i: 0.01, d: 10}

# ============================================================
# Left leg joints
# ============================================================

# Hip forward/backward turn (x)
hip_f_joint_left_position_controller:
  type: effort_controllers/JointPositionController
  joint: hip_f_joint_left
  pid: {p: 400.0, i: 0.1, d: 1.0}

# Hip side turn (y)
hip_s_joint_left_position_controller:
  type: effort_controllers/JointPositionController
  joint: hip_s_joint_left
  pid: {p: 1200.0, i: 0.1, d: 2.0}

# hip rotate (z)
hip_r_joint_left_position_controller:
  type: effort_controllers/JointPositionController
  joint: hip_r_joint_left
  pid: {p: 400.0, i: 0.1, d: 1.0}

# Knee forward/backward turn (x)
knee_joint_left_position_controller:
  type: effort_controllers/JointPositionController
  joint: knee_joint_left
  pid: {p: 400.0, i: 0.1, d: 1.0}

# Ancle side turn (y)
ankle_s_joint_left_position_controller:
  type: effort_controllers/JointPositionController
  joint: ankle_s_joint_left
  pid: {p: 400.0, i: 0.1, d: 1.0}

# Ancle forward/backward turn (x)
ankle_f_joint_left_position_controller:
  type: effort_controllers/JointPositionController
  joint: ankle_f_joint_left
  pid: {p: 400.0, i: 0.1, d: 1.0}

# ============================================================
# Right leg joints
# ============================================================

# Hip forward/backward turn (x)
hip_f_joint_right_position_controller:
  type: effort_controllers/JointPositionController
  joint: hip_f_joint_right
  pid: {p: 400.0, i: 0.1, d: 1.0}

# Hip side turn (y)
hip_s_joint_right_position_controller:
  type: effort_controllers/JointPositionController
  joint: hip_s_joint_right
  pid: {p: 1200.0, i: 0.1, d: 2.0}

# hip rotate (z)
hip_r_joint_right_position_controller:
  type: effort_controllers/JointPositionController
  joint: hip_r_joint_right
  pid: {p: 400.0, i: 0.1, d: 1.0}

# Knee forward/backward turn (x)
knee_joint_right_position_controller:
  type: effort_controllers/JointPositionController
  joint: knee_joint_right
  pid: {p: 400.0, i: 0.1, d: 1.0}

# Ancle side turn (y)
ankle_s_joint_right_position_controller:
  type: effort_controllers/JointPositionController
  joint: ankle_s_joint_right
  pid: {p: 400.0, i: 0.1, d: 1.0}

# Ancle forward/backward turn (x)
ankle_f_joint_right_position_controller:
  type: effort_controllers/JointPositionController
  joint: ankle_f_joint_right
  pid: {p: 400.0, i: 0.1, d: 1.0}